server:
  port: 9090
  address: 192.168.1.103
  sessionTimeout: 30
  contextPath: /
---
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.gyex.webwite.entity
---
spring:
  datasource:
    name: website
    url: jdbc:mysql://localhost:3306/website?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver